apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://localhost:8086
    database: sensors
    isDefault: true
    jsonData:
      httpMode: GET
      keepCookies: []
      version: InfluxQL
    secureJsonData: {}
    version: 1
    editable: true