---
system:
  certificateFilePath: ""
  privateKeyPath: ""
  rootCaPath: ""
  rootpath: "/greengrass/v2"
  thingName: "local-greengrass-core"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.12.0"
    configuration:
      awsRegion: "us-east-1"
      iotRoleAlias: ""
      iotDataEndpoint: ""
      iotCredEndpoint: ""
      interpolateComponentConfiguration: true
      deploymentPollingFrequency: 15
      jvmOptions: "-Dlog.store=FILE"
      logging:
        level: "INFO"
        fileSizeKB: 1024
        totalLogsSizeKB: 25600
        format: "TEXT"
      platformOverride: {}
      runWithDefault:
        posixUser: "ggc_user:ggc_group"
      componentStoreMaxSizeBytes: 10000000000
      deploymentMaxWaitTimeSeconds: 120
      mqtt:
        port: 1883
        maxInFlightPublishes: 5
        maxPublishRetry: 2
  aws.greengrass.Labs.LocalDebugConsole:
    componentType: "PLUGIN"
    version: "2.2.5"
    configuration:
      httpsEnabled: false
      bindHostname: "0.0.0.0"
      port: 1441
  # Official AWS Greengrass Labs components
  aws.greengrass.labs.dashboard.InfluxDBGrafana:
    componentType: "GENERIC"
    version: "2.0.7"
    configuration:
      InfluxDBPort: 8086
      InfluxDBDataPath: "/greengrass/v2/work/influxdb"
      GrafanaPort: 3000
      GrafanaDataPath: "/greengrass/v2/work/grafana"
      BridgeNetworkName: "greengrass-telemetry-bridge"
  aws.greengrass.labs.telemetry.InfluxDBPublisher:
    componentType: "GENERIC"
    version: "1.0.0"
    configuration:
      PublishInterval: 5
      OutputMetrics: true
  # Custom components
  com.edge.llm.SensorSimulator:
    componentType: "GENERIC"
    version: "1.0.0"
    configuration:
      sensorCount: 5
      samplingIntervalMs: 5000
      anomalyProbability: 0.05
  com.edge.llm.InferenceEngine:
    componentType: "GENERIC"
    version: "1.0.0"
    configuration:
      modelName: "TinyLlama-1.1B-Chat"
      batchSize: 10
      inferenceIntervalMs: 30000
      temperature: 0.7
  com.edge.llm.ChatBotUI:
    componentType: "GENERIC"
    version: "1.0.0"
    configuration:
      webPort: 8080
      chatHistoryLimit: 50
      enableDebugMode: true
  com.edge.llm.TelemetryBridge:
    componentType: "GENERIC"
    version: "1.0.0"
    configuration:
      sensorTopics: ["local/sensors/+"]
      analysisTopics: ["local/analysis/results"]
      dashboardPort: 3000